/**
 * AI Services for Mind Buddy
 *
 * This file provides TypeScript services for all AI features:
 * - Sentiment Analysis: Analyzes emotional tone of journal entries
 * - Chat (Sereni): Conversational AI assistant for mental wellness
 * - Insights: Personalized wellness tips and recommendations
 *
 * All services use the authenticated API instance from authService
 */

import api from './authService';

// ==========================================
// TYPE DEFINITIONS
// ==========================================

/**
 * Sentiment scores returned by the AI model
 * Each score is between 0 and 1, representing confidence levels
 */
export interface SentimentScores {
  positive: number;
  negative: number;
  neutral: number;
}

/**
 * Complete sentiment analysis result
 * Includes the detected sentiment, scores, emotions, and crisis flags
 */
export interface SentimentResult {
  _id: string;
  user_id: string;
  journal_entry_id?: string;
  sentiment_label: 'positive' | 'negative' | 'neutral';
  sentiment_scores: SentimentScores;
  detected_emotions: string[];
  crisis_flag: boolean;
  crisis_keywords?: string[];
  created_at: string;
  updated_at: string;
}

/**
 * Response from sentiment analysis endpoint
 * Includes both the sentiment result and any generated insights
 */
export interface AnalyzeSentimentResponse {
  sentiment: SentimentResult;
  insights: WellnessInsight[];
}

/**
 * Analysis of sentiment trends over time
 */
export interface SentimentTrendAnalysis {
  overall_trend: 'improving' | 'declining' | 'stable' | 'fluctuating';
  average_sentiment: 'positive' | 'negative' | 'neutral';
  sentiment_distribution: {
    positive: number;
    negative: number;
    neutral: number;
  };
  risk_level: 'low' | 'moderate' | 'high' | 'critical';
  recommendation: string;
}

/**
 * A single chat message in a conversation
 */
export interface ChatMessage {
  _id: string;
  user_id: string;
  conversation_id: string;
  message: string;
  role: 'user' | 'assistant';
  ai_response?: string;
  sentiment?: string;
  created_at: string;
}

/**
 * Response from sending a chat message
 */
export interface ChatResponse {
  conversation_id: string;
  user_message: string;
  ai_response: string;
  sentiment: string;
  source: string;
  requires_professional_help: boolean;
  chat_id: string;
}

/**
 * Wellness insight generated by the AI
 */
export interface WellnessInsight {
  _id: string;
  user_id: string;
  insight_type:
    | 'daily_tip'
    | 'mood_pattern'
    | 'crisis_support'
    | 'wellness_recommendation';
  insight_text: string;
  recommendation?: string;
  activity_suggestion?: string;
  priority: 'low' | 'normal' | 'high' | 'urgent';
  is_read: boolean;
  is_dismissed: boolean;
  based_on_sentiment?: string;
  based_on_pattern?: string;
  created_at: string;
  updated_at: string;
  read_at?: string;
}

// ==========================================
// SENTIMENT ANALYSIS SERVICES
// ==========================================

export const analyzeSentiment = async (
  text: string,
  journalEntryId?: string
): Promise<AnalyzeSentimentResponse> => {
  const response = await api.post('/sentiment/analyze', {
    text,
    journal_entry_id: journalEntryId,
  });
  return response.data;
};

export const getSentimentHistory = async (
  limit: number = 30,
  days: number = 30
): Promise<{ history: SentimentResult[]; count: number }> => {
  const response = await api.get('/sentiment/history', {
    params: { limit, days },
  });
  return response.data;
};

export const getSentimentTrends = async (
  days: number = 30
): Promise<{
  trend_analysis: SentimentTrendAnalysis;
  sentiment_distribution: any;
  pattern_insight: WellnessInsight | null;
}> => {
  const response = await api.get('/sentiment/trends', {
    params: { days },
  });
  return response.data;
};

export const checkCrisisFlags = async (
  days: number = 7
): Promise<{
  has_crisis_flags: boolean;
  crisis_count: number;
  recent_crises: SentimentResult[];
}> => {
  const response = await api.get('/sentiment/crisis-check', {
    params: { days },
  });
  return response.data;
};

// ==========================================
// CHAT SERVICES (Sereni AI Assistant)
// ==========================================

export const sendChatMessage = async (
  message: string,
  conversationId?: string
): Promise<ChatResponse> => {
  const response = await api.post('/chat/message', {
    message,
    conversation_id: conversationId,
  });
  return response.data;
};

export const getConversations = async (
  limit: number = 10
): Promise<{ conversations: any[]; count: number }> => {
  const response = await api.get('/chat/conversations', {
    params: { limit },
  });
  return response.data;
};

export const getConversation = async (
  conversationId: string,
  limit: number = 50
): Promise<{ conversation_id: string; messages: ChatMessage[]; count: number }> => {
  const response = await api.get(`/chat/conversation/${conversationId}`, {
    params: { limit },
  });
  return response.data;
};

export const getChatHistory = async (
  limit: number = 50
): Promise<{ history: ChatMessage[]; count: number }> => {
  const response = await api.get('/chat/history', {
    params: { limit },
  });
  return response.data;
};

export const getProactiveCheckIn = async (): Promise<{
  message: string;
  type: string;
}> => {
  const response = await api.get('/chat/proactive-check-in');
  return response.data;
};

// ==========================================
// INSIGHTS SERVICES
// ==========================================

export const getInsights = async (
  limit: number = 10,
  unreadOnly: boolean = false
): Promise<{ insights: WellnessInsight[]; count: number }> => {
  const response = await api.get('/insights', {
    params: { limit, unread_only: unreadOnly },
  });
  return response.data;
};

export const getUrgentInsights = async (): Promise<{
  urgent_insights: WellnessInsight[];
  count: number;
  has_urgent: boolean;
}> => {
  const response = await api.get('/insights/urgent');
  return response.data;
};

export const getDailyInsight = async (): Promise<{
  insight: WellnessInsight | null;
  is_new: boolean;
}> => {
  const response = await api.get('/insights/daily');
  // backend always sends { insight: {...}, is_new: bool } but let's be safe
  return {
    insight: response.data.insight ?? null,
    is_new: response.data.is_new ?? false,
  };
};

export const markInsightRead = async (insightId: string): Promise<{
  message: string;
  insight: WellnessInsight;
}> => {
  const response = await api.put(`/insights/${insightId}/read`);
  return response.data;
};

export const dismissInsight = async (insightId: string): Promise<{
  message: string;
  insight: WellnessInsight;
}> => {
  const response = await api.put(`/insights/${insightId}/dismiss`);
  return response.data;
};

export const generateInsight = async (
  type: 'wellness_recommendation' | 'mood_pattern' = 'wellness_recommendation'
): Promise<{
  message: string;
  insight: WellnessInsight;
}> => {
  const response = await api.post('/insights/generate', { type });
  return response.data;
};

// ✅ FIXED: point to the actual backend route your Flask blueprint exposes
export const analyzeJournalEntry = async (entryText: string): Promise<{
  insight: string;
}> => {
  // your backend route is /ai_insights/analyze (from routes/ai_insights.py)
  const response = await api.post('/ai_insights/analyze', {
    entry: entryText,
  });
  return response.data;
};
